# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2.3.1
    - name: get-cmake
      uses: lukka/get-cmake@v3.18.0
    - name: Install apt packages
      run: sudo apt install mesa-common-dev libglu1-mesa-dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Fast install dependencies
      run: npm ci
    - name: Run webpack production build
      run: npm run build
    - name: Check if app runs
      run: npm start
