# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DiscordQt CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fast install dependencies and build
        run: SKIP_BUILD=1 npm ci
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: DiscordQt-master-win32-x64
          path: ${{ github.workspace }}/dist
      - name: Pack binaries
        run: npm run package
      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: DiscordQt-master-win32-x64
          path: ${{ github.workspace }}/deploy/win32/build/Discord-Qt/

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fast install dependencies and build
        run: SKIP_BUILD=1 npm ci
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: DiscordQt-master-linux-x64
          path: ${{ github.workspace }}/dist
      - name: Pack binaries
        run: npm run package
      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: DiscordQt-master-linux-x64.AppImage
          path: ${{ github.workspace }}/deploy/linux/build/Discord-Qt/DiscordQt-x86_64.AppImage
